### PR TITLE
Add tor hidden service

### PR DESCRIPTION
**Pull request by imaginaryusername**
@HostFat has tested the tor server and it seems to work. Must use with a Tor proxy obviously.

### CODE REVIEW

**Comment by cculianu** [comment]
Hmm.  What's the UX if user doesn't have Tor running?  It's "hurr durr.. server error".

Ideally we would do more than offer user a broken option -- like detect if they are running Tor -- and only show that server in that case....

**Comment by cculianu** [comment]
I'll merge this -- but this now needs additional work possibly to hide it if no tor. :/

**Comment by imaginaryusername** [comment]
Indeed there can be a hide mechanism if there's no proxy - but really, will normal users who don't know tor stray from the default and grab this weird looking "dfgosjgnhfdiogjnffdojbnsbjkbn.onion" server? =)

Jokes aside, yes a hide mechanism will be helpful, even if it's not that high a priority.

**Comment by cculianu** [comment]
On second thought as I used it --  I realized user gets instant-feedback that it's broken.  it's fine.

Will leave as-is.

**Pull request merged**
